### ISSUE TITLE
Cmd('git') failed due to: exit code(128)

### ISSUE THREAD

**Issue by ShimingLee** [StackStorm/stackstorm-k8s#290]
I'm having a git problem, does anyone know how to fix it  ？
```
root@stackstorm-st2client-7d5f5b67d8-qlc9f:/opt/stackstorm# st2 pack install xml

For the "xml" pack, the following content will be registered:

actions   |  2
rules     |  0
sensors   |  0
aliases   |  0
triggers  |  0

Installation may take a while for packs with many items.

        [ succeeded ] init_task
        [  failed   ] download_pack

id: 621c2521835b36700fc4b060
action.ref: packs.install
parameters:
  packs:
  - xml
status: failed
start_timestamp: Mon, 28 Feb 2022 01:28:01 UTC
end_timestamp: Mon, 28 Feb 2022 01:30:05 UTC
log:
  - status: requested
    timestamp: '2022-02-28T01:28:01.832000Z'
  - status: scheduled
    timestamp: '2022-02-28T01:28:01.896000Z'
  - status: running
    timestamp: '2022-02-28T01:28:01.946000Z'
  - status: failed
    timestamp: '2022-02-28T01:30:05.379000Z'
result:
  errors:
  - message: Execution failed. See result for details.
    result:
      exit_code: 1
      result: None
      stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 214, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 101, in run
    logger=self.logger,
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/pack_management.py", line 165, in download_pack
    ref=pack_version,
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/pack_management.py", line 205, in clone_repo
    repo = Repo.clone_from(repo_url, temp_dir)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/git/repo/base.py", line 1087, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/git/repo/base.py", line 1018, in _clone
    finalize_process, decode_streams=False)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/git/cmd.py", line 116, in handle_process_output
    return finalizer(process)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/git/util.py", line 354, in finalize_process
    proc.wait(**kwargs)
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/git/cmd.py", line 409, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --progress https://github.com/StackStorm-Exchange/stackstorm-xml /root/ca86e2f4859d2c8f082f4a9e7a7b840e
"
      stdout: ''
    task_id: download_pack
    type: error
  output:
    conflict_list: null
    message: ''
    packs_list: null
    warning_list: null

```

**Comment by anrajme** [comment]
@ShimingLee  st2 pack instal won't work directly inside the pods by the default design. 

> - The st2packs method is the default. st2 pack install does not work because this chart (by default) uses read-only emptyDir volumes for /opt/stackstorm/{packs,virtualenvs}. Instead, you need to bake the packs into a custom docker image, push it to a private or public docker registry and reference that image in Helm values.

https://github.com/StackStorm/stackstorm-ha#method-1-st2packs-images-the-default

You may need to refer one of these methods mentioned above. cheers!

**Comment by cognifloyd** [comment]
Can you share some of your values?
- `st2.packs.images`
- `st2.packs.volumes`

**Comment by cognifloyd** [comment]
@ShimingLee Have you resolved this issue? I'm going to assume so and close this in January 2023 if you haven't responded.

**Comment by cognifloyd** [comment]
I'm assuming this is resolved.
