### ISSUE TITLE
mongodb connection failed in k8s

### ISSUE THREAD

**Issue by chain312** [StackStorm/stackstorm-k8s#335]
When I started stackstorm with helm install stackstorm -f stackstorm.yaml Stackstorm-ha, mongodb failed to connect
```
2022-11-29 13:02:49,700 INFO [-] Using Python: 3.8.10 (/opt/stackstorm/st2/bin/python)
2022-11-29 13:02:49,700 INFO [-] Using fs encoding: utf-8, default encoding: utf-8, locale: en_US.UTF-8, LANG env variable: en_US.UTF-8, PYTHONIOENCODING env variable: notset
2022-11-29 13:02:49,701 INFO [-] Using config files: /etc/st2/st2.conf,/etc/st2/st2.docker.conf,/etc/st2/st2.user.conf
2022-11-29 13:02:49,701 INFO [-] Using logging config: /etc/st2/logging.actionrunner.conf
2022-11-29 13:02:49,701 INFO [-] Using coordination driver: redis
2022-11-29 13:02:49,701 INFO [-] Using metrics driver: noop
2022-11-29 13:02:49,712 INFO [-] Connecting to database "st2" @ "stackstorm-mongodb-0.stackstorm-mongodb-headless:27017,stackstorm-mongodb-1.stackstorm-mongodb-headless:27017,stackstorm-mongodb-2.stackstorm-mongodb-headless:27017 (replica set)" as user "st2-admin".
2022-11-29 13:02:52,722 ERROR [-] Failed to connect to database "st2" @ "stackstorm-mongodb-0.stackstorm-mongodb-headless:27017,stackstorm-mongodb-1.stackstorm-mongodb-headless:27017,stackstorm-mongodb-2.stackstorm-mongodb-headless:27017 (replica set)" as user "st2-admin": No replica set members found yet, Timeout: 3.0s, Topology Description: <TopologyDescription id: 638602f9ded1a053b4dcfeba, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('stackstorm-mongodb-0.stackstorm-mongodb-headless', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('stackstorm-mongodb-1.stackstorm-mongodb-headless', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('stackstorm-mongodb-2.stackstorm-mongodb-headless', 27017) server_type: Unknown, rtt: None>]>
2022-11-29 13:02:52,723 ERROR [-] (PID=1) Worker quit due to exception.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2actions/cmd/actionrunner.py", line 99, in main
    _setup()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2actions/cmd/actionrunner.py", line 53, in _setup
    common_setup(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/service_setup.py", line 252, in setup
    db_setup()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/database_setup.py", line 55, in db_setup
    connection = db_init.db_setup_with_retry(**db_cfg)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/persistence/db_init.py", line 79, in db_setup_with_retry
    return db_func_with_retry(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/persistence/db_init.py", line 58, in db_func_with_retry
    return retrying_obj.call(db_func, *args, **kwargs)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/six.py", line 696, in reraise
    raise value
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/models/db/__init__.py", line 239, in db_setup
    connection = _db_connect(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/models/db/__init__.py", line 213, in _db_connect
    raise e
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/models/db/__init__.py", line 204, in _db_connect
    connection.admin.command("ping")
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/database.py", line 736, in command
    with self.__client._socket_for_reads(
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1325, in _socket_for_reads
    server = self._select_server(read_preference, session)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1278, in _select_server
    server = topology.select_server(server_selector)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/topology.py", line 241, in select_server
    return random.choice(self.select_servers(selector,
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/topology.py", line 199, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/pymongo/topology.py", line 215, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: No replica set members found yet, Timeout: 3.0s, Topology Description: <TopologyDescription id: 638602f9ded1a053b4dcfeba, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('stackstorm-mongodb-0.stackstorm-mongodb-headless', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('stackstorm-mongodb-1.stackstorm-mongodb-headless', 27017) server_type: Unknown, rtt: None>, <ServerDescription ('stackstorm-mongodb-2.stackstorm-mongodb-headless', 27017) server_type: Unknown, rtt: None>]>
```
stackstorm.yaml 
```
st2:
  config: |
    [api]
    allow_origin = '*'
    [messaging]
    url = amqp://admin:9jSw1u07NbHtZke1mjW4Cj@stackstorm-rabbitmq-headless:5672/
    [content]
    index_url=http://gitea:3000/soar/sec-soar-pack/raw/master/v1/index.json
    [coordination]
    url = redis://redis-node-0.redis-headless:26379?sentinel=mymaster&sentinel_fallback=redis-node-1.redis-headless:26379
  packs:
    volumes:
      enabled: true
      packs:
        nfs:
          server: 192.168.192.3 
          path: /data/docker_share/packs
      virtualenvs:
        nfs:
          server: 192.168.192.3 
          path: /data/docker_share/virtualenvs
      configs: 
        nfs:
          server: 192.168.192.3
          path: /data/docker_share/config
st2actionrunner:
  postStartScript: "echo -e '[global]\nindex-url = http://devpi:3141/root/dev/+simple\n\n[install]' > /etc/pip.conf"
rabbitmq:
  auth:
    password: 9jSw1u07NbHtZke1mjW4Cj
mongodb:
  image:
    tag: 4.4
rabbitmq:
  image:
    tag: 3.8
redis:
  enabled: false
  image:
    tag: 6.2.7
  sentinel:
    image:
      tag: 6.2.7
  replica:
    replicaCount: 2
  auth:
    enabled: false
    sentinel: false
```
How to solve the mongo link problem

**Comment by arms11** [comment]
typically in the Kubernetes deployment it can be found in `/etc/st2/st2.docker.conf` to my knowledge.

**Comment by chain312** [comment]
> typically in the Kubernetes deployment it can be found in `/etc/st2/st2.docker.conf` to my knowledge.
@arms11 
It should be the network problem of k8s. I changed to a separate mongo to connect successfully

**Comment by guzzijones** [comment]
I increased the database timeouts in the config overrides and now I am getting dns errors

**Comment by chain312** [comment]
@guzzijones Thank you, I also tried this operation, I will look at the problem of DNS later.

**Comment by cognifloyd** [comment]
For dns issues, try setting `dnsConfig.searches`, and any other `dnsConfig` settings needed by your cluster.
