### ISSUE TITLE
email pack is failing to send emails

### ISSUE THREAD

**Issue by lingaswamy143** [StackStorm/stackstorm-k8s#350]
stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 214, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/email/actions/send_email.py", line 54, in run
    s = SMTP(account_data['server'], int(account_data['port']), timeout=20)
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

**Comment by cognifloyd** [comment]
@lingaswamy143 Why did you file this issue in the stackstorm-k8s repo? Are you running StackStorm in kubernetes?

It looks like you are running an action from the email pack:
https://github.com/StackStorm-Exchange/stackstorm-email

What version of StackStorm? What version of the pack?
