### ISSUE TITLE
There is an issue with the StackStorm Kafka pack in stackstorm 3.8.0

### ISSUE THREAD

**Issue by Bindu-yadav8** [StackStorm/stackstorm-k8s#376]
It seems that the Kafka pack is not compatible with st2 3.8.0, on Python 3.8.10. I am currently experiencing an issue with the StackStorm Kafka pack, and I'm reaching out to the community for assistance.

Seeing invalid syntax error (uses a newly reserved keyword: async)

`st2 run kafka.produce topic=test message='StackStorm meets Apache Kafka'`

> stderr: "Traceback (most recent call last):
>   File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 264, in _get_action_instance
>     actions_cls = action_loader.register_plugin(Action, self._file_path)
>   File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/util/loader.py", line 173, in register_plugin
>     module = imp.load_source(module_name, plugin_abs_file_path)
>   File "/usr/lib/python3.8/imp.py", line 171, in load_source
>     module = _load(spec)
>   File "<frozen importlib._bootstrap>", line 702, in _load
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/opt/stackstorm/packs/kafka/actions/produce.py", line 2, in <module>
>     from kafka import SimpleProducer, KafkaClient
>   File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/__init__.py", line 12, in <module>
>     from kafka.producer import SimpleProducer, KeyedProducer
>   File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/producer/__init__.py", line 1, in <module>
>     from .simple import SimpleProducer
>   File "/opt/stackstorm/virtualenvs/kafka/lib/python3.8/site-packages/kafka/producer/simple.py", line 58
>     return '<SimpleProducer batch=%s>' % self.async
>                                               ^
> SyntaxError: invalid syntax`

If anyone has experience with this issue or suggestions for troubleshooting, I would greatly appreciate your insights.

Thank you in advance for your time and assistance.

@armab

**Comment by Bindu-yadav8** [comment]
Posted in the wrong respository. hence closing
