### ISSUE TITLE
Error while installing multiple packs via configs

### ISSUE THREAD

**Issue by akshat-rubrik** [StackStorm/stackstorm-k8s#387]
Hey community, i'm trying to install packs using k8s helm chart, but running into an error while doing helm upgrade.
config in `values.yaml`:
```
configs:
      core.yaml: |
        ---
        # example core pack config yaml
      pagerduty.yaml: |
        api_key: abcd
        service_key: abcd
        debug: false
        ---
      jira.yaml: |
        api_key: abcd
        ---
```
error in `job-st2-register-content`:
```
2024-01-24 00:37:59,098 WARNING [-] Failed to register configs: Failed to register config "/opt/stackstorm/configs/jira.yaml" for pack "jira": expected a single document in the stream
  in "/opt/stackstorm/configs/jira.yaml", line 1, column 1
but found another document
  in "/opt/stackstorm/configs/jira.yaml", line 2, column 1
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/configsregistrar.py", line 84, in register_from_packs
    self._register_config_for_pack(pack=pack_name, config_path=config_path)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/configsregistrar.py", line 129, in _register_config_for_pack
    values = self._meta_loader.load(config_path)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/loader.py", line 253, in load
    result = self._load(PARSER_FUNCS[file_ext], file_path)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/loader.py", line 265, in _load
    return parser_func(fd)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/constants/meta.py", line 53, in yaml_safe_load
    return yaml.load(stream, Loader=YamlSafeLoader)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 719, in yaml._yaml.CParser.get_single_node
yaml.composer.ComposerError: expected a single document in the stream
  in "/opt/stackstorm/configs/jira.yaml", line 1, column 1
but found another document
  in "/opt/stackstorm/configs/jira.yaml", line 2, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/st2-register-content", line 22, in <module>
    sys.exit(content_loader.main(sys.argv[1:]))
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 458, in main
    register_content()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 404, in register_content
    register_configs()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 388, in register_configs
    raise e
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/content/bootstrap.py", line 378, in register_configs
    registered_count = configs_registrar.register_configs(
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/configsregistrar.py", line 188, in register_configs
    result = registrar.register_from_packs(base_dirs=packs_base_paths)
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/st2common/bootstrap/configsregistrar.py", line 92, in register_from_packs
    raise ValueError(msg)
ValueError: Failed to register config "/opt/stackstorm/configs/jira.yaml" for pack "jira": expected a single document in the stream
  in "/opt/stackstorm/configs/jira.yaml", line 1, column 1
but found another document
  in "/opt/stackstorm/configs/jira.yaml", line 2, column 1
```

Solution: https://stackoverflow.com/questions/14359557/reading-yaml-file-with-python-results-in-yaml-composer-composererror-expected-a

**Comment by akshat-rubrik** [comment]
Figured out that the `---` should be at the start of the yaml.
Correct config: 
```configs:
      core.yaml: |
        ---
        # example core pack config yaml
      pagerduty.yaml: |
        ---
        api_key: abcd
        service_key: abcd
        debug: false
        
      jira.yaml: |
        ---
        api_key: abcd
```
